import {
    Accordion,
    AccordionContent,
    AccordionItem,
    AccordionTrigger,
  } from "./ui/accordion";
  
  export function AccordionDemo() {
    return (
      <Accordion type="single" collapsible className="w-full">
        <AccordionItem value="item-4">
          <AccordionTrigger>What is ContentTura AI?</AccordionTrigger>
          <AccordionContent>
            ContentTura AI is an AI-powered tool designed to help users create high-quality social media content quickly and efficiently.
          </AccordionContent>
        </AccordionItem>
  
        <AccordionItem value="item-5">
          <AccordionTrigger>Can ContentTura AI generate content for all social media platforms?</AccordionTrigger>
          <AccordionContent>
            Yes, ContentTura AI can generate content tailored for platforms like Instagram, Twitter, LinkedIn, Facebook, and more.
          </AccordionContent>
        </AccordionItem>
  
        <AccordionItem value="item-6">
          <AccordionTrigger>How customizable is the generated content?</AccordionTrigger>
          <AccordionContent>
            The content generated by ContentTura AI is highly customizable, allowing you to adjust tone, style, and format to match your brand’s voice.
          </AccordionContent>
        </AccordionItem>
  
        <AccordionItem value="item-7">
          <AccordionTrigger>Does ContentTura AI support multiple languages?</AccordionTrigger>
          <AccordionContent>
            Yes, ContentTura AI supports multiple languages, allowing you to create content for a global audience.
          </AccordionContent>
        </AccordionItem>
  
        <AccordionItem value="item-8">
          <AccordionTrigger>Is there a free version of ContentTura AI?</AccordionTrigger>
          <AccordionContent>
            Yes, ContentTura AI offers a free plan with limited features. For more advanced options, paid plans are available.
          </AccordionContent>
        </AccordionItem>
      </Accordion>
    );
  }
  